default:
    image: node:latest

build-job:
    stage: build
    script:
        - yarn
        - yarn build
deploy-job:
    stage: deploy
    script:
        - echo deploy
test-job:
    stage: test
    script:
        - yarn test

