version: '3.3'
services:
  web:
    image: hello-brunch
    build: .
    ports:
      - "80:80"
    logging:
      driver: loki
      options:
        loki-url: "http://10.250.14.1:3100/loki/api/v1/push" 
